/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Usuario;

import BD.conexaoBD;
import DAO.ContatoDAO;
import Modelo.Contato;
import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.sql.Date;
import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author 825155650
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(247, 239, 219));
    }
    
    public Cadastro(int id){
    initComponents();
    ContatoDAO contatoDao = new ContatoDAO();
    Contato contato = contatoDao.getContatoById(id);
    nomeField.setText(contato.getNome());
    telefoneField.setText(contato.getTelefone());
    emailField.setText(contato.getEmail());
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    CPFField.setText(formato.format(contato.getCPF()));
    loginField.setText(contato.getLogin());
    senhaField.setText(contato.getSenha());
    confirmeField.setText(contato.getSenha());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        telefoneLabel = new javax.swing.JLabel();
        telefoneField = new javax.swing.JFormattedTextField();
        nascimentoLabel = new javax.swing.JLabel();
        CPFField = new javax.swing.JFormattedTextField();
        loginLabel = new javax.swing.JLabel();
        loginField = new javax.swing.JTextField();
        senhaLabel = new javax.swing.JLabel();
        senhaField = new javax.swing.JPasswordField();
        confirmeLabel = new javax.swing.JLabel();
        confirmeField = new javax.swing.JPasswordField();
        buttonCadastrar = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1109, 781));
        getContentPane().setLayout(null);

        panel1.setBackground(new java.awt.Color(246, 231, 203));
        panel1.setEnabled(false);
        panel1.setLayout(null);

        label1.setFont(new java.awt.Font("Dialog", 0, 50)); // NOI18N
        label1.setForeground(new java.awt.Color(198, 180, 148));
        label1.setText("mais sobre");
        panel1.add(label1);
        label1.setBounds(300, 160, 249, 57);

        label2.setFont(new java.awt.Font("Dialog", 1, 52)); // NOI18N
        label2.setForeground(new java.awt.Color(110, 101, 85));
        label2.setText("Nos conte um pouco");
        panel1.add(label2);
        label2.setBounds(160, 100, 520, 71);

        label3.setFont(new java.awt.Font("Dialog", 1, 52)); // NOI18N
        label3.setForeground(new java.awt.Color(110, 101, 85));
        label3.setText("você!");
        panel1.add(label3);
        label3.setBounds(350, 220, 133, 51);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastroSemente.png"))); // NOI18N
        panel1.add(jLabel1);
        jLabel1.setBounds(-40, 180, 970, 600);

        getContentPane().add(panel1);
        panel1.setBounds(260, 0, 855, 780);

        nomeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nomeLabel.setForeground(new java.awt.Color(198, 180, 148));
        nomeLabel.setText("Primeiro nome:");
        getContentPane().add(nomeLabel);
        nomeLabel.setBounds(20, 190, 130, 17);

        nomeField.setBorder(null);
        nomeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nomeField);
        nomeField.setBounds(20, 210, 210, 33);

        emailLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(198, 180, 148));
        emailLabel.setText("E-mail:");
        getContentPane().add(emailLabel);
        emailLabel.setBounds(20, 250, 50, 13);

        emailField.setBorder(null);
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailField);
        emailField.setBounds(20, 270, 210, 33);

        telefoneLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        telefoneLabel.setForeground(new java.awt.Color(198, 180, 148));
        telefoneLabel.setText("Telefone:");
        getContentPane().add(telefoneLabel);
        telefoneLabel.setBounds(20, 310, 70, 17);

        telefoneField.setBorder(null);
        try {
            telefoneField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefoneField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        telefoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneFieldActionPerformed(evt);
            }
        });
        getContentPane().add(telefoneField);
        telefoneField.setBounds(20, 330, 210, 33);

        nascimentoLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nascimentoLabel.setForeground(new java.awt.Color(198, 180, 148));
        nascimentoLabel.setText("CPF:");
        getContentPane().add(nascimentoLabel);
        nascimentoLabel.setBounds(20, 370, 40, 17);

        CPFField.setBorder(null);
        try {
            CPFField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CPFField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CPFField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPFFieldActionPerformed(evt);
            }
        });
        getContentPane().add(CPFField);
        CPFField.setBounds(20, 390, 210, 33);

        loginLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(198, 180, 148));
        loginLabel.setText("Login:");
        getContentPane().add(loginLabel);
        loginLabel.setBounds(20, 430, 50, 17);

        loginField.setAlignmentX(0.0F);
        loginField.setAlignmentY(0.0F);
        loginField.setBorder(null);
        loginField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginFieldActionPerformed(evt);
            }
        });
        getContentPane().add(loginField);
        loginField.setBounds(20, 450, 210, 33);

        senhaLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        senhaLabel.setForeground(new java.awt.Color(198, 180, 148));
        senhaLabel.setText("Senha:");
        getContentPane().add(senhaLabel);
        senhaLabel.setBounds(20, 490, 50, 17);

        senhaField.setAutoscrolls(false);
        senhaField.setBorder(null);
        senhaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaFieldActionPerformed(evt);
            }
        });
        getContentPane().add(senhaField);
        senhaField.setBounds(20, 510, 210, 33);

        confirmeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirmeLabel.setForeground(new java.awt.Color(198, 180, 148));
        confirmeLabel.setText("Confirme:");
        getContentPane().add(confirmeLabel);
        confirmeLabel.setBounds(20, 550, 70, 17);

        confirmeField.setBorder(null);
        confirmeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmeFieldActionPerformed(evt);
            }
        });
        getContentPane().add(confirmeField);
        confirmeField.setBounds(20, 570, 210, 33);

        buttonCadastrar.setBackground(new java.awt.Color(218, 213, 200));
        buttonCadastrar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonCadastrar.setText("Cadastrar");
        buttonCadastrar.setBorder(null);
        buttonCadastrar.setBorderPainted(false);
        buttonCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonCadastrar.setDefaultCapable(false);
        buttonCadastrar.setFocusable(false);
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCadastrar);
        buttonCadastrar.setBounds(70, 650, 120, 50);

        Voltar.setBackground(new java.awt.Color(218, 213, 200));
        Voltar.setFont(new java.awt.Font("Sans Serif Collection", 0, 10)); // NOI18N
        Voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltar.png"))); // NOI18N
        Voltar.setFocusable(false);
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar);
        Voltar.setBounds(6, 6, 40, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 70, 70, 70);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
        Connection conexao = new conexaoBD().getConnection();
        String login;
        String nome;
        String telefone;
        String msg = "";
        boolean validacao = false;
        String senha;
        String confirme;
        String email;
        String CPF;

        senha = new String (senhaField.getPassword());
        confirme = new String (confirmeField.getPassword());
        login = loginField.getText();
        nome = nomeField.getText();
        telefone = telefoneField.getText();
        email = emailField.getText();
        CPF = CPFField.getText();

        if (login.equals("")){
            validacao = true;
            msg += "\nLogin";
        }

        if (email.equals("")){
            validacao = true;
            msg += "\nE-mail";
        }

        if (nome.equals("")){
            validacao = true;
            msg += "\nNome";
        }
        if (telefone.equals("")){
            validacao = true;
            msg += "\nTelefone";
        }

        if (senha.equals("")){
            validacao = true;
            msg += "\nSenha";
        }

        if (confirme.equals("")){
            validacao = true;
            msg += "\nConfirmação";
        }
        if (!confirme.equals(senha)){
            validacao = true;
            msg += "\nA confirmação de senha está incorreta";
        }

        if (validacao == true) {
            JOptionPane.showMessageDialog(null, "Está faltando os seguintes preenchimentos:" + msg);
        }

        else {
            
            ContatoDAO contatoDAO = new ContatoDAO();

                if (contatoDAO.existeUsuario(login, email, CPF)) {
                    JOptionPane.showMessageDialog(null, "OPA! Este usuário já existe. Tente outro e-mail, login ou CPF.");
                    return;
                }
            Contato contato = new Contato();
            contato.setNome(nome);
            contato.setTelefone(telefone);
            contato.setEmail(email);
            contato.setLogin(login);
            contato.setSenha(senha);
            contato.setCPF(CPF);
            contatoDAO.adicionaContato(contato);
            JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso!");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCadastrarActionPerformed

    private void confirmeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmeFieldActionPerformed

    private void senhaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaFieldActionPerformed

    private void loginFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFieldActionPerformed

    private void CPFFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPFFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPFFieldActionPerformed

    private void telefoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void nomeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField CPFField;
    private javax.swing.JButton Voltar;
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JPasswordField confirmeField;
    private javax.swing.JLabel confirmeLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JTextField loginField;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel nascimentoLabel;
    private javax.swing.JTextField nomeField;
    private javax.swing.JLabel nomeLabel;
    private java.awt.Panel panel1;
    private javax.swing.JPasswordField senhaField;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JFormattedTextField telefoneField;
    private javax.swing.JLabel telefoneLabel;
    // End of variables declaration//GEN-END:variables
}
