/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface.Usuario;

import Interface.funcionario.*;
import BD.conexaoBD;
import DAO.ContatoDAO;
import Modelo.Contato;
import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import static Interface.Usuario.Login.nomeUsuarioLogado;


/**
 *
 * @author jonat
 */
public class ModificarUsuario extends javax.swing.JFrame {
    /**
     * Creates new form Modificar
     */
    public ModificarUsuario() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(247,239,219));
    }
    
    private int id;

    public ModificarUsuario(int id){
    this.id = id;
    initComponents();
    ContatoDAO contatoDao = new ContatoDAO();
    Contato contato = contatoDao.getContatoById(id);
    nomeField.setText(contato.getNome());
    telefoneField.setText(contato.getTelefone());
    emailField.setText(contato.getEmail());
    CPFField.setText(contato.getCPF());
    loginField.setText(contato.getLogin());
    senhaField.setText(contato.getSenha());
    confirmeField.setText(contato.getSenha());
    getContentPane().setBackground(new java.awt.Color(247, 239, 219));
   
    }

    /**x
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginField = new javax.swing.JTextField();
        senhaLabel = new javax.swing.JLabel();
        senhaField = new javax.swing.JPasswordField();
        confirmeLabel = new javax.swing.JLabel();
        confirmeField = new javax.swing.JPasswordField();
        Alterar = new javax.swing.JToggleButton();
        nomeLabel = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        telefoneLabel = new javax.swing.JLabel();
        telefoneField = new javax.swing.JFormattedTextField();
        nascimentoLabel = new javax.swing.JLabel();
        CPFField = new javax.swing.JFormattedTextField();
        loginLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(980, 780));
        setMinimumSize(new java.awt.Dimension(980, 780));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel1.setLayout(null);

        loginField.setBackground(new java.awt.Color(242, 242, 242));
        loginField.setAlignmentX(0.0F);
        loginField.setAlignmentY(0.0F);
        loginField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        loginField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginFieldActionPerformed(evt);
            }
        });
        jPanel1.add(loginField);
        loginField.setBounds(62, 318, 280, 32);

        senhaLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        senhaLabel.setForeground(new java.awt.Color(198, 180, 148));
        senhaLabel.setText("Senha:");
        jPanel1.add(senhaLabel);
        senhaLabel.setBounds(62, 356, 48, 17);

        senhaField.setBackground(new java.awt.Color(242, 242, 242));
        senhaField.setAutoscrolls(false);
        senhaField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        senhaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaFieldActionPerformed(evt);
            }
        });
        jPanel1.add(senhaField);
        senhaField.setBounds(62, 379, 280, 32);

        confirmeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirmeLabel.setForeground(new java.awt.Color(198, 180, 148));
        confirmeLabel.setText("Confirme:");
        jPanel1.add(confirmeLabel);
        confirmeLabel.setBounds(62, 417, 68, 17);

        confirmeField.setBackground(new java.awt.Color(242, 242, 242));
        confirmeField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        confirmeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmeFieldActionPerformed(evt);
            }
        });
        jPanel1.add(confirmeField);
        confirmeField.setBounds(62, 440, 280, 32);

        Alterar.setBackground(new java.awt.Color(218, 213, 200));
        Alterar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });
        jPanel1.add(Alterar);
        Alterar.setBounds(150, 520, 103, 42);

        nomeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nomeLabel.setForeground(new java.awt.Color(198, 180, 148));
        nomeLabel.setText("Nome:");
        jPanel1.add(nomeLabel);
        nomeLabel.setBounds(62, 46, 46, 17);

        nomeField.setBackground(new java.awt.Color(242, 242, 242));
        nomeField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        nomeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFieldActionPerformed(evt);
            }
        });
        jPanel1.add(nomeField);
        nomeField.setBounds(61, 69, 280, 32);

        emailLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(198, 180, 148));
        emailLabel.setText("E-mail:");
        jPanel1.add(emailLabel);
        emailLabel.setBounds(62, 113, 47, 13);

        emailField.setBackground(new java.awt.Color(242, 242, 242));
        emailField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        jPanel1.add(emailField);
        emailField.setBounds(61, 132, 280, 32);

        telefoneLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        telefoneLabel.setForeground(new java.awt.Color(198, 180, 148));
        telefoneLabel.setText("Telefone:");
        jPanel1.add(telefoneLabel);
        telefoneLabel.setBounds(62, 176, 64, 17);

        telefoneField.setBackground(new java.awt.Color(242, 242, 242));
        telefoneField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        try {
            telefoneField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefoneField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        telefoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneFieldActionPerformed(evt);
            }
        });
        jPanel1.add(telefoneField);
        telefoneField.setBounds(61, 199, 280, 32);

        nascimentoLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nascimentoLabel.setForeground(new java.awt.Color(198, 180, 148));
        nascimentoLabel.setText("CPF");
        jPanel1.add(nascimentoLabel);
        nascimentoLabel.setBounds(62, 237, 27, 17);

        CPFField.setBackground(new java.awt.Color(242, 242, 242));
        CPFField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        try {
            CPFField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CPFField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CPFField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPFFieldActionPerformed(evt);
            }
        });
        jPanel1.add(CPFField);
        CPFField.setBounds(62, 260, 280, 32);

        loginLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(198, 180, 148));
        loginLabel.setText("Login:");
        jPanel1.add(loginLabel);
        loginLabel.setBounds(62, 295, 43, 17);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(280, 60, 400, 630);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cidade.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 180, 970, 650);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(110, 101, 85));
        jLabel3.setText("Está de cara nova?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 130, 370, 47);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(198, 180, 148));
        jLabel1.setText("Altere suas credencias");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 170, 250, 22);

        voltar.setBackground(new java.awt.Color(218, 213, 200));
        voltar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltar.png"))); // NOI18N
        voltar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voltar.setFocusable(false);
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(900, 20, 50, 50);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CPFFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPFFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPFFieldActionPerformed

    private void telefoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void nomeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFieldActionPerformed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
        Connection conexao = new conexaoBD().getConnection();
        String login = loginField.getText();
        String nome = nomeField.getText();
        String telefone = telefoneField.getText();
        String msg = "";
        boolean validacao = false;
        String senha = new String (senhaField.getPassword());;
        String confirme = new String (confirmeField.getPassword());
        String  email = emailField.getText();
        String CPF = CPFField.getText();

        if (login.equals("")){
            validacao = true;
            msg += "\nlogin";
        }

        if (email.equals("")){
            validacao = true;
            msg += "\nE-mail";
        }

        if (nome.equals("")){
            validacao = true;
            msg += "\nNome";
        }
        if (telefone.equals("")){
            validacao = true;
            msg += "\nTelefone";
        }

        if (senha.equals("")){
            validacao = true;
            msg += "\nsenha";
        }

        if (confirme.equals("")){
            validacao = true;
            msg += "\nconfirmação";
        }
        if (!confirme.equals(senha)){
            validacao = true;
            msg += "\nA confirmação de senha está incorreta";
        }

        if (validacao == true) {
            JOptionPane.showMessageDialog(null, "Está faltando os seguintes preenchimentos:" + msg);
        }

        else {
            nomeUsuarioLogado = nome;
            System.out.println(id);
            Contato contato = new Contato();
            contato.setId(id);
            contato.setNome(nome);
            contato.setTelefone(telefone);
            contato.setEmail(email);
            contato.setLogin(login);
            contato.setSenha(senha);
            contato.setCPF(CPF);
            ContatoDAO contatoDAO = new ContatoDAO();
            contatoDAO.atualizarContato(contato);
            JOptionPane.showMessageDialog(null, "Usuário atualizado com sucesso!");
            this.dispose();
            new SelecaoUsuario().setVisible(true);
        }
    }//GEN-LAST:event_AlterarActionPerformed

    private void confirmeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmeFieldActionPerformed

    private void senhaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaFieldActionPerformed

    private void loginFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginFieldActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        new SelecaoUsuario().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Alterar;
    private javax.swing.JFormattedTextField CPFField;
    private javax.swing.JPasswordField confirmeField;
    private javax.swing.JLabel confirmeLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField loginField;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel nascimentoLabel;
    private javax.swing.JTextField nomeField;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JPasswordField senhaField;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JFormattedTextField telefoneField;
    private javax.swing.JLabel telefoneLabel;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
