/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface.Usuario;

import static Interface.Usuario.Login.idUsuarioLogado;
import static Interface.Usuario.Login.nomeUsuarioLogado;


/**
 *
 * @author jonat
 */
public class SelecaoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form SelecaoUsuario
     */
    public SelecaoUsuario() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(248, 240, 220));
        jLabel4.setText("Bem-vindo, " + nomeUsuarioLogado + "!");        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Alterar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Apoiados = new javax.swing.JButton();
        Sementes = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1073, 785));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/comunidadeSelecao.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 525, 550, 222);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/raifu.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 170, 441, 270);

        Alterar.setBackground(new java.awt.Color(218, 213, 200));
        Alterar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Alterar.setText("Alterar meus dados");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });
        getContentPane().add(Alterar);
        Alterar.setBounds(10, 10, 140, 50);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 38)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(110, 101, 85));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Bem-vindo, Jonathas!");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 80, 710, 60);

        Apoiados.setBackground(new java.awt.Color(218, 213, 200));
        Apoiados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Apoiados.setText("Apoiados");
        Apoiados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApoiadosActionPerformed(evt);
            }
        });
        getContentPane().add(Apoiados);
        Apoiados.setBounds(760, 360, 180, 160);

        Sementes.setBackground(new java.awt.Color(218, 213, 200));
        Sementes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Sementes.setText("Sementes");
        Sementes.setToolTipText("");
        Sementes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SementesActionPerformed(evt);
            }
        });
        getContentPane().add(Sementes);
        Sementes.setBounds(120, 350, 180, 160);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Visualizar todas:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 330, 100, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Gerenciar meus:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(760, 340, 100, 17);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
        this.dispose();
        new ModificarUsuario(idUsuarioLogado).setVisible(true);
    }//GEN-LAST:event_AlterarActionPerformed

    private void ApoiadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApoiadosActionPerformed
        this.dispose();
        new FormulariosSalvos().setVisible(true);
    }//GEN-LAST:event_ApoiadosActionPerformed

    private void SementesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SementesActionPerformed
        this.dispose();
        new usuarioFormularios().setVisible(true);
    }//GEN-LAST:event_SementesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecaoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelecaoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.JButton Apoiados;
    private javax.swing.JButton Sementes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
