/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface.Usuario;

import DAO.ConexaoFormulario;
import static Interface.Usuario.Login.idUsuarioLogado;
import Interface.funcionario.VisualizarFormulario;
import Modelo.ContatoFormulario;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import BD.conexaoBD;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author jonat
 */
public class usuarioFormularios extends javax.swing.JFrame {

    /**
     * Creates new form usuarioFormularios
     */
    public usuarioFormularios() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(236, 236, 220));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFormularios = new javax.swing.JTable();
        home = new javax.swing.JButton();
        visualizar = new javax.swing.JButton();
        Apoiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1055, 810));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(110, 101, 85));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nossas sementes");
        jLabel1.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(6, 6, 313, 60);

        tblFormularios.setAutoCreateRowSorter(true);
        tblFormularios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Data", "Nome", "Idade", "Área de Interesse", "Descrição", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFormularios);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(6, 72, 924, 683);

        home.setBackground(new java.awt.Color(218, 213, 200));
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/home.png"))); // NOI18N
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home);
        home.setBounds(942, 685, 80, 70);

        visualizar.setBackground(new java.awt.Color(218, 213, 200));
        visualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/visualizar.png"))); // NOI18N
        visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarActionPerformed(evt);
            }
        });
        getContentPane().add(visualizar);
        visualizar.setBounds(942, 158, 80, 70);

        Apoiar.setBackground(new java.awt.Color(218, 213, 200));
        Apoiar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Apoiar.setText("Apoiar");
        Apoiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApoiarActionPerformed(evt);
            }
        });
        getContentPane().add(Apoiar);
        Apoiar.setBounds(942, 72, 80, 74);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sementes.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 0, 75, 75);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
       this.dispose();
       new SelecaoUsuario().setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ConexaoFormulario formularioDao = new ConexaoFormulario(); 
      DefaultTableModel model = (DefaultTableModel) tblFormularios.getModel();
        model.setRowCount(0);

    for (ContatoFormulario formulario : formularioDao.listaFormularios()) {
    model.addRow(new Object[]{
        formulario.getId(),
        formulario.getData(),
        formulario.getNome(),
        formulario.getIdade(),
        formulario.getAreaInteresse(),
        formulario.getDescricao(),
        formulario.getStatus()
    });
    }
    }//GEN-LAST:event_formWindowOpened

    private void visualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarActionPerformed
        if(tblFormularios.getSelectedRowCount () == 1){
            int row = tblFormularios.getSelectedRow();
            int id = Integer.parseInt(tblFormularios.getValueAt(row, 0).toString());
            new VisualizarFormulario(id).setVisible(true);
        }

        else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
    }//GEN-LAST:event_visualizarActionPerformed

    private void ApoiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApoiarActionPerformed
            int row = tblFormularios.getSelectedRow();

            int resposta = JOptionPane.showConfirmDialog(null, "Deseja apoiar essa nossa semente?");
            if (resposta == JOptionPane.YES_OPTION) {
                if (row != -1) {
                    int idFormulario = Integer.parseInt(tblFormularios.getValueAt(row, 0).toString());
                    String Status = tblFormularios.getValueAt(row, 6).toString();

                    if (!Status.equals("Em Apoio")) {
                        ConexaoFormulario dao = new ConexaoFormulario();
                        boolean sucesso = dao.salvarFormularioParaUsuario(idUsuarioLogado, idFormulario);

                        if (sucesso) {
                            ContatoFormulario formulario = new ContatoFormulario();
                            formulario.setId(idFormulario);
                            formulario.setStatus("Em Apoio");

                            // Atualiza no banco
                            dao.atualizarStatus(formulario);

                            // Atualiza na tabela visível
                            tblFormularios.setValueAt("Em Apoio", row, 6);
                            atualizarTabela();

                            JOptionPane.showMessageDialog(null, "Formulário salvo com sucesso!");
                        } else {
                            JOptionPane.showMessageDialog(null, "Este formulário já foi salvo.");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Essa semente já está sendo regada!");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Selecione um formulário para salvar.");
                }
            }
    }//GEN-LAST:event_ApoiarActionPerformed

     public void atualizarTabela() {
    ConexaoFormulario contatoFormulario = new ConexaoFormulario();
    DefaultTableModel model = (DefaultTableModel) tblFormularios.getModel();

    // Limpa a tabela antes de atualizar
    model.setRowCount(0);

    // Recarrega os dados atualizados
    for (ContatoFormulario formulario : contatoFormulario.listaFormularios()) {
        model.addRow(new Object[]{
            formulario.getId(),
            formulario.getData(),
            formulario.getNome(),
            formulario.getIdade(),
            formulario.getAreaInteresse(),
            formulario.getDescricao(),
            formulario.getStatus()
        });
      }
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuarioFormularios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuarioFormularios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuarioFormularios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuarioFormularios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuarioFormularios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Apoiar;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFormularios;
    private javax.swing.JButton visualizar;
    // End of variables declaration//GEN-END:variables
}
