/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Interface.funcionario.LoginFuncionario;
import Interface.Usuario.Login;

/**
 *
 * @author jonat
 */
public class Inicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaIncial
     */
    public Inicial() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(248, 240, 220));        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entrarApoiador = new javax.swing.JButton();
        entrarFuncionario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1060, 809));
        getContentPane().setLayout(null);

        entrarApoiador.setBackground(new java.awt.Color(218, 213, 200));
        entrarApoiador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        entrarApoiador.setForeground(new java.awt.Color(198, 180, 148));
        entrarApoiador.setText("Apoiador\n");
        entrarApoiador.setBorder(null);
        entrarApoiador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entrarApoiador.setFocusable(false);
        entrarApoiador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarApoiadorActionPerformed(evt);
            }
        });
        getContentPane().add(entrarApoiador);
        entrarApoiador.setBounds(760, 290, 185, 147);

        entrarFuncionario.setBackground(new java.awt.Color(218, 213, 200));
        entrarFuncionario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        entrarFuncionario.setForeground(new java.awt.Color(198, 180, 148));
        entrarFuncionario.setText("Funcionário\n");
        entrarFuncionario.setToolTipText("");
        entrarFuncionario.setBorder(null);
        entrarFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entrarFuncionario.setFocusable(false);
        entrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(entrarFuncionario);
        entrarFuncionario.setBounds(122, 285, 185, 147);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/comunidade.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-20, 490, 1050, 318);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(110, 101, 85));
        jLabel3.setText("Entrar como:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(760, 270, 100, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(110, 101, 85));
        jLabel4.setText("Entrar como:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(122, 264, 90, 17);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/raifu.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 50, 400, 369);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void entrarApoiadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarApoiadorActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_entrarApoiadorActionPerformed

    private void entrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarFuncionarioActionPerformed
        this.dispose();
        new LoginFuncionario().setVisible(true);
    }//GEN-LAST:event_entrarFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton entrarApoiador;
    private javax.swing.JButton entrarFuncionario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
