/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface.funcionario;

import BD.conexaoBD;
import DAO.ConexaoFormulario;
import Modelo.ContatoFormulario;
import java.sql.Connection;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author jonat
 */
public class editarFormulario extends javax.swing.JFrame {

    private int id;

    /**
     * Creates new form editarFormulario
     */
    public editarFormulario() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(236, 236, 220));
        descricaoField.setLineWrap(true);     
        descricaoField.setWrapStyleWord(true); 

    }
    
    public editarFormulario(int id){
    
    this.id = id;
    initComponents();
    
    ConexaoFormulario contatoFormulario = new ConexaoFormulario();
    ContatoFormulario contato = contatoFormulario.getFormularioById(id);

    nomeField.setText(contato.getNome());

    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
    dataField.setText(formato.format(contato.getData()));
    System.out.println(contato.getIdade());
    String idadeTexto = contato.getIdade(); 
    idadeTexto = idadeTexto.replaceAll("[^0-9]", ""); 
    int idade = Integer.parseInt(idadeTexto);
    idadeField.setValue(idade);
    areaInteresseField.setText(contato.getAreaInteresse());
    descricaoField.setText(contato.getDescricao()); // Corrigido
    getContentPane().setBackground(new java.awt.Color(236, 236, 220));
    descricaoField.setLineWrap(true);     
    descricaoField.setWrapStyleWord(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        nomeField = new javax.swing.JTextField();
        idadeField = new javax.swing.JSpinner();
        areaInteresseField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaoField = new javax.swing.JTextArea();
        Atualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dataField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1129, 803));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(252, 247, 234));
        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 52)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(110, 101, 85));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Atualize os dados");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 80, 470, 71);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(110, 101, 85));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Semente!");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(130, 190, 250, 64);

        jLabel9.setBackground(new java.awt.Color(198, 180, 148));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(198, 180, 148));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("da nossa pequena");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(80, 150, 350, 44);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/arvore.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(70, 260, 360, 450);

        voltar.setBackground(new java.awt.Color(218, 213, 200));
        voltar.setForeground(new java.awt.Color(198, 180, 148));
        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltar.png"))); // NOI18N
        voltar.setFocusable(false);
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        jPanel1.add(voltar);
        voltar.setBounds(10, 703, 50, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 529, 764);

        nomeField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 101, 85)));
        nomeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nomeField);
        nomeField.setBounds(550, 40, 510, 48);

        idadeField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idadeField.setBorder(null);
        idadeField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(idadeField);
        idadeField.setBounds(820, 110, 160, 48);

        areaInteresseField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        areaInteresseField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 101, 85)));
        getContentPane().add(areaInteresseField);
        areaInteresseField.setBounds(550, 190, 510, 48);

        descricaoField.setColumns(20);
        descricaoField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descricaoField.setRows(5);
        descricaoField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(198, 180, 148)));
        jScrollPane1.setViewportView(descricaoField);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(550, 280, 510, 400);

        Atualizar.setBackground(new java.awt.Color(218, 213, 200));
        Atualizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Atualizar.setForeground(new java.awt.Color(198, 180, 148));
        Atualizar.setText("Atualizar");
        Atualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Atualizar.setFocusable(false);
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(Atualizar);
        Atualizar.setBounds(710, 690, 204, 64);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(110, 101, 85));
        jLabel3.setText("Idade:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(820, 90, 46, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(110, 101, 85));
        jLabel4.setText("Área de Interesse:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(550, 170, 128, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(110, 101, 85));
        jLabel5.setText("Descreva a situação do candidato:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(550, 250, 270, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(110, 101, 85));
        jLabel6.setText("Nome:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(550, 10, 46, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(110, 101, 85));
        jLabel10.setText("Data:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(550, 90, 37, 17);

        dataField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 101, 85)));
        try {
            dataField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dataField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(dataField);
        dataField.setBounds(550, 110, 230, 48);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        int naoAlterar = JOptionPane.showConfirmDialog(null,"Deseja sair sem salvar as alterações?");
        if (naoAlterar == JOptionPane.YES_OPTION){
            this.dispose();
            new FuncionarioFormularios().setVisible(true);
        } 
    }//GEN-LAST:event_voltarActionPerformed

    private void nomeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFieldActionPerformed

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
         Connection conexao = new conexaoBD().getConnection();

        String nome = nomeField.getText();
        String idadeNF = idadeField.getValue().toString();
        String idade = idadeNF + " Anos";

        String areaInteresse = areaInteresseField.getText();
        String descricao = descricaoField.getText();
        String status = "Solicitação em Aberto";
        Date data = null;

        String faltaPreencher = "";
        boolean validacao = true;

        // Conversão da data com tratamento de erro
        try {
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            data = new Date(format.parse(dataField.getText()).getTime());
        } catch (ParseException e) {
            validacao = false;
            faltaPreencher += "\nData de Nascimento (inválida)";
        }

        // Validações
        if (nome.equals("")) {
            validacao = false;
            faltaPreencher += "\nNome";
        }

        if (idadeNF == null || idadeNF.equals("0")) {
            validacao = false;
            faltaPreencher += "\nIdade";
        }

        if (areaInteresse.equals("") || areaInteresse.equals("Selecione")) {
            validacao = false;
            faltaPreencher += "\nÁrea de Interesse";
        }

        if (descricao.equals("")) {
            validacao = false;
            faltaPreencher += "\nDescrição";
        }

        // Resultado da validação
        if (!validacao) {
            JOptionPane.showMessageDialog(null, "Falta preencher os campos:\n" + faltaPreencher);
        } else {
            ContatoFormulario formulario = new ContatoFormulario();
            formulario.setId(id);
            formulario.setNome(nome);
            formulario.setIdade(idade);
            formulario.setAreaInteresse(areaInteresse);
            formulario.setDescricao(descricao);
            formulario.setStatus(status);
            formulario.setData(data);

            ConexaoFormulario contatoFormulario = new ConexaoFormulario();
            contatoFormulario.atualizarFormulario(formulario);

            JOptionPane.showMessageDialog(null, "Formulário atualizado com sucesso!");
            this.dispose();
            new FuncionarioFormularios().setVisible(true);

        }        
    }//GEN-LAST:event_AtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editarFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editarFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editarFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editarFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editarFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualizar;
    private javax.swing.JTextField areaInteresseField;
    private javax.swing.JFormattedTextField dataField;
    private javax.swing.JTextArea descricaoField;
    private javax.swing.JSpinner idadeField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeField;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
