/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface.funcionario;

import BD.conexaoBD;
import DAO.ContatoDAO;
import DAO.ConexaoFormulario;
import Interface.funcionario.TelaSelecao;
import Modelo.ContatoFormulario;
import java.sql.Connection;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author jonat
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(236, 236, 220));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeField = new javax.swing.JTextField();
        idadeField = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        areaInteresseField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaoField = new javax.swing.JTextArea();
        Enviar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nascimentoField = new javax.swing.JFormattedTextField();
        dataField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1129, 803));
        getContentPane().setLayout(null);

        nomeField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 101, 85)));
        nomeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nomeField);
        nomeField.setBounds(558, 35, 520, 48);

        idadeField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idadeField.setBorder(null);
        idadeField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(idadeField);
        idadeField.setBounds(830, 110, 160, 48);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(110, 101, 85));
        jLabel1.setText("Anos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1000, 110, 48, 48);

        areaInteresseField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        areaInteresseField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 101, 85)));
        getContentPane().add(areaInteresseField);
        areaInteresseField.setBounds(558, 193, 520, 48);

        descricaoField.setColumns(20);
        descricaoField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descricaoField.setRows(5);
        descricaoField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(198, 180, 148)));
        jScrollPane1.setViewportView(descricaoField);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(558, 279, 520, 400);

        Enviar.setBackground(new java.awt.Color(218, 213, 200));
        Enviar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Enviar.setForeground(new java.awt.Color(198, 180, 148));
        Enviar.setText("Enviar");
        Enviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Enviar.setFocusable(false);
        Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarActionPerformed(evt);
            }
        });
        getContentPane().add(Enviar);
        Enviar.setBounds(716, 691, 204, 64);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(247, 239, 219));
        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1064, 12, 41, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(110, 101, 85));
        jLabel3.setText("Idade:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(830, 90, 46, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(110, 101, 85));
        jLabel4.setText("Área de Interesse:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(558, 169, 128, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(110, 101, 85));
        jLabel5.setText("Descreva a situação do candidato:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(558, 253, 270, 17);

        jPanel1.setBackground(new java.awt.Color(252, 247, 234));
        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 52)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(110, 101, 85));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Fale um pouco");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 80, 440, 71);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(110, 101, 85));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Semente!");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(140, 190, 250, 64);

        jLabel9.setBackground(new java.awt.Color(198, 180, 148));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(198, 180, 148));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Sobre nossa pequena");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(90, 150, 350, 44);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/arvore.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(80, 260, 360, 450);

        voltar.setBackground(new java.awt.Color(218, 213, 200));
        voltar.setForeground(new java.awt.Color(198, 180, 148));
        voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltar.png"))); // NOI18N
        voltar.setFocusable(false);
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        jPanel1.add(voltar);
        voltar.setBounds(10, 703, 50, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 529, 764);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(110, 101, 85));
        jLabel6.setText("Nome:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(558, 9, 46, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(110, 101, 85));
        jLabel10.setText("Data:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(560, 90, 37, 17);

        nascimentoField.setBorder(null);
        try {
            nascimentoField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        nascimentoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nascimentoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nascimentoFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nascimentoField);
        nascimentoField.setBounds(0, 0, 64, 16);

        dataField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 101, 85)));
        try {
            dataField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dataField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(dataField);
        dataField.setBounds(560, 110, 230, 48);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeFieldActionPerformed

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
      Connection conexao = new conexaoBD().getConnection();

String nome = nomeField.getText();
String idadeNF = idadeField.getValue().toString();
String idade = idadeNF + " Anos";

String areaInteresse = areaInteresseField.getText();
String descricao = descricaoField.getText();
String status = "Solicitação em Aberto";
Date data = null;

String faltaPreencher = "";
boolean validacao = true;

// Conversão da data com tratamento de erro
try {
    SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
    data = new Date(format.parse(dataField.getText()).getTime());
} catch (ParseException e) {
    validacao = false;
    faltaPreencher += "\nData de Nascimento (inválida)";
}

// Validações
if (nome.equals("")) {
    validacao = false;
    faltaPreencher += "\nNome";
}

if (idadeNF == null || idadeNF.equals("0")) {
    validacao = false;
    faltaPreencher += "\nIdade";
}

if (areaInteresse.equals("") || areaInteresse.equals("Selecione")) {
    validacao = false;
    faltaPreencher += "\nÁrea de Interesse";
}

if (descricao.equals("")) {
    validacao = false;
    faltaPreencher += "\nDescrição";
}

// Resultado da validação
if (!validacao) {
    JOptionPane.showMessageDialog(null, "Falta preencher os campos:\n" + faltaPreencher);
} else {
    ContatoFormulario formulario = new ContatoFormulario();
    formulario.setNome(nome);
    formulario.setIdade(idade);
    formulario.setAreaInteresse(areaInteresse);
    formulario.setDescricao(descricao);
    formulario.setStatus(status);
    formulario.setData(data);

    ConexaoFormulario contatoFormulario = new ConexaoFormulario();
    contatoFormulario.EnviarFormulario(formulario);

    JOptionPane.showMessageDialog(null, "Formulário enviado com sucesso!");
}

      
     
      
/*
        try {
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            dataNascimento = new Date(format.parse(nascimentoField.getText()).getTime());
        }

        catch (ParseException e){
            throw new RuntimeException(e);
        }

        if (login.equals("")){
            validacao = true;
            msg += "\nlogin";
        }

        if (email.equals("")){
            validacao = true;
            msg += "\nE-mail";
        }

        if (nome.equals("")){
            validacao = true;
            msg += "\nNome";
        }
        if (telefone.equals("")){
            validacao = true;
            msg += "\nTelefone";
        }

        if (senha.equals("")){
            validacao = true;
            msg += "\nsenha";
        }

        if (confirme.equals("")){
            validacao = true;
            msg += "\nconfirmação";
        }
        if (!confirme.equals(senha)){
            validacao = true;
            msg += "\nA confirmação de senha está incorreta";
        }

        if (validacao == true) {
            JOptionPane.showMessageDialog(null, "Está faltando os seguintes preenchimentos:" + msg);
        }

        else {
            Contato contato = new Contato();
            contato.setNome(nome);
            contato.setTelefone(telefone);
            contato.setEmail(email);
            contato.setLogin(login);
            contato.setSenha(senha);
            contato.setDataNascimento(dataNascimento);
            ContatoDAO contatoDAO = new ContatoDAO();
            contatoDAO.adicionaContato(contato);
            JOptionPane.showMessageDialog(null, "Usuário cadastrado com sucesso!");
        }
      */
    }//GEN-LAST:event_EnviarActionPerformed

    private void nascimentoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nascimentoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nascimentoFieldActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        this.dispose();
        new TelaSelecao().setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enviar;
    private javax.swing.JTextField areaInteresseField;
    private javax.swing.JFormattedTextField dataField;
    private javax.swing.JTextArea descricaoField;
    private javax.swing.JSpinner idadeField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField nascimentoField;
    private javax.swing.JTextField nomeField;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
