/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.funcionario;

import Interface.funcionario.Modificar;
import DAO.ContatoDAO;
import Modelo.Contato;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Interface.funcionario.TelaSelecao;
/**
 *
 * @author 825155650
 */
public class Gerenciamento extends javax.swing.JFrame {

    /**
     * Creates new form LoginPrincipal
     */
    public Gerenciamento() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(236, 236, 220));
        tblContatos.setRowHeight(30);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblContatos = new javax.swing.JTable();
        tblModificar = new javax.swing.JButton();
        tblApagar = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(218, 213, 200));
        setMinimumSize(new java.awt.Dimension(1122, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        tblContatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblContatos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblContatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Telefone", "E-mail", "CPF", "Login"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblContatos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tblContatos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(16, 64, 980, 690);

        tblModificar.setBackground(new java.awt.Color(218, 213, 200));
        tblModificar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblModificar.setText("Modificar");
        tblModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblModificarActionPerformed(evt);
            }
        });
        getContentPane().add(tblModificar);
        tblModificar.setBounds(1010, 70, 80, 70);

        tblApagar.setBackground(new java.awt.Color(218, 213, 200));
        tblApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        tblApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblApagarActionPerformed(evt);
            }
        });
        getContentPane().add(tblApagar);
        tblApagar.setBounds(1010, 150, 80, 70);

        home.setBackground(new java.awt.Color(218, 213, 200));
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/home.png"))); // NOI18N
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home);
        home.setBounds(1010, 680, 80, 70);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(110, 101, 85));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nossos colaboradores");
        jLabel1.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 420, 60);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblApagarActionPerformed
        if(tblContatos.getSelectedRowCount () == 1){
        int row = tblContatos.getSelectedRow();
        int id = Integer.parseInt(tblContatos.getValueAt(row, 0).toString());
        int resposta = JOptionPane.showConfirmDialog(null, "Desejar deletar esse usuário?");
        if (resposta == JOptionPane.YES_OPTION){
           ContatoDAO contatoDao =  new ContatoDAO();
           contatoDao.deletarUsuarioPorId(id);
           atualizarTabela();
       }
        }
        
        else {
        JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
    }//GEN-LAST:event_tblApagarActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
       this.dispose();
        new TelaSelecao().setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    ContatoDAO contatoDao = new ContatoDAO();
    DefaultTableModel model = (DefaultTableModel) tblContatos.getModel();

// Limpa a tabela antes de atualizar
    model.setRowCount(0);

    // Recarrega os dados atualizados
    for (Contato contato : contatoDao.listaContatos()) {
        model.addRow(new Object[]{
            contato.getId(),
            contato.getNome(),
            contato.getTelefone(),
            contato.getEmail(),
            contato.getCPF(),
            contato.getLogin()
        });
}
    }//GEN-LAST:event_formWindowOpened

    private void tblModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblModificarActionPerformed
        if(tblContatos.getSelectedRowCount () == 1){
        int row = tblContatos.getSelectedRow();
        int id = Integer.parseInt(tblContatos.getValueAt(row, 0).toString());
        new Modificar(id).setVisible(true);
        this.dispose();
        }
        
        else {
        JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }
    }//GEN-LAST:event_tblModificarActionPerformed

    
    public void atualizarTabela() {
    ContatoDAO contatoDao = new ContatoDAO();
    DefaultTableModel model = (DefaultTableModel) tblContatos.getModel();

    // Limpa a tabela antes de atualizar
    model.setRowCount(0);

    // Recarrega os dados atualizados
    for (Contato contato : contatoDao.listaContatos()) {
        model.addRow(new Object[]{
            contato.getId(),
            contato.getNome(),
            contato.getTelefone(),
            contato.getEmail(),
            contato.getCPF(),
            contato.getLogin()
        });
    }
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gerenciamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tblApagar;
    private javax.swing.JTable tblContatos;
    private javax.swing.JButton tblModificar;
    // End of variables declaration//GEN-END:variables
}
