/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface.funcionario;

import DAO.ConexaoFuncionario;
import Interface.Inicial;
import Interface.Inicial;
import Interface.funcionario.Gerenciamento;
import javax.swing.JOptionPane;

/**
 *
 * @author jonat
 */
public class LoginFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form LoginFuncionario
     */
    public LoginFuncionario() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(247, 239, 219));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldLogin = new javax.swing.JTextField();
        fieldSenha = new javax.swing.JPasswordField();
        buttonLogin = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelLogin1 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        label4 = new java.awt.Label();
        labelLogin3 = new javax.swing.JLabel();
        label5 = new java.awt.Label();
        labelSenha1 = new javax.swing.JLabel();
        labelLogin2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1069, 743));
        setResizable(false);
        getContentPane().setLayout(null);

        fieldLogin.setBorder(null);
        fieldLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(fieldLogin);
        fieldLogin.setBounds(30, 280, 160, 33);

        fieldSenha.setBorder(null);
        fieldSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(fieldSenha);
        fieldSenha.setBounds(30, 340, 160, 33);

        buttonLogin.setBackground(new java.awt.Color(218, 213, 200));
        buttonLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonLogin.setText("Entrar");
        buttonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        getContentPane().add(buttonLogin);
        buttonLogin.setBounds(70, 390, 72, 40);

        jButton1.setBackground(new java.awt.Color(218, 213, 200));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltar.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(85, 650, 40, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icone.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 70, 70, 80);

        labelLogin1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelLogin1.setForeground(new java.awt.Color(198, 180, 148));
        labelLogin1.setText("Login");
        getContentPane().add(labelLogin1);
        labelLogin1.setBounds(30, 260, 50, 17);

        panel1.setBackground(new java.awt.Color(255, 252, 245));
        panel1.setLayout(null);

        label4.setFont(new java.awt.Font("Dialog", 0, 52)); // NOI18N
        label4.setForeground(new java.awt.Color(110, 101, 85));
        label4.setText("Bem-vindo de volta!");
        panel1.add(label4);
        label4.setBounds(10, 300, 465, 71);

        labelLogin3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelLogin3.setForeground(new java.awt.Color(198, 180, 148));
        labelLogin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/maos.png"))); // NOI18N
        labelLogin3.setText("Login");
        panel1.add(labelLogin3);
        labelLogin3.setBounds(90, 470, 770, 273);

        label5.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        label5.setForeground(new java.awt.Color(198, 180, 148));
        label5.setText("O que vamos fazer hoje?");
        panel1.add(label5);
        label5.setBounds(10, 370, 404, 51);

        getContentPane().add(panel1);
        panel1.setBounds(218, 0, 0, 740);

        labelSenha1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelSenha1.setForeground(new java.awt.Color(198, 180, 148));
        labelSenha1.setText("Senha");
        getContentPane().add(labelSenha1);
        labelSenha1.setBounds(30, 320, 60, 17);

        labelLogin2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelLogin2.setForeground(new java.awt.Color(198, 180, 148));
        labelLogin2.setText("Login");
        getContentPane().add(labelLogin2);
        labelLogin2.setBounds(30, 260, 50, 17);

        jPanel1.setBackground(new java.awt.Color(255, 250, 238));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(198, 180, 148));
        jLabel2.setText("O que vamos fazer hoje?");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 350, 540, 64);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 52)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(110, 101, 85));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/maos.png"))); // NOI18N
        jLabel3.setText("Bem-vindo de volta!");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 490, 760, 260);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 52)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(110, 101, 85));
        jLabel4.setText("Bem-vindo de volta!");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 280, 500, 63);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(220, 0, 850, 750);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        String login;
        String senha;
        login = fieldLogin.getText();
        senha = new String(fieldSenha.getPassword());
        if (!login.equals("") && !senha.equals("")) {
            ConexaoFuncionario funcionario = new ConexaoFuncionario();
            if (funcionario.login(login, senha)) {
                JOptionPane.showMessageDialog(null, "Login efetuado com sucesso");
                new TelaSelecao().setVisible(true);
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Login inválido");
        }
    }//GEN-LAST:event_buttonLoginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Inicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogin;
    private javax.swing.JTextField fieldLogin;
    private javax.swing.JPasswordField fieldSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private javax.swing.JLabel labelLogin1;
    private javax.swing.JLabel labelLogin2;
    private javax.swing.JLabel labelLogin3;
    private javax.swing.JLabel labelSenha1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
