/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface.funcionario;

/**
 *
 * @author jonat
 */
public class TelaSelecao extends javax.swing.JFrame {

    /**
     * Creates new form TelaSelecao
     */
    public TelaSelecao() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(236, 236, 220));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        usuarioButton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        formularioButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        ListaFormularios = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1069, 745));
        getContentPane().setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Gerenciamento de:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(210, 460, 130, 20);

        usuarioButton.setBackground(new java.awt.Color(218, 213, 200));
        usuarioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usuarioButton.setText("Usuários");
        usuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(usuarioButton);
        usuarioButton.setBounds(180, 480, 190, 160);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Preenchimento de:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(450, 460, 150, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/raifuFuncionarios.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(380, 40, 300, 350);

        formularioButton1.setBackground(new java.awt.Color(218, 213, 200));
        formularioButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        formularioButton1.setText("Formulário");
        formularioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formularioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(formularioButton1);
        formularioButton1.setBounds(430, 480, 190, 160);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Gerenciamento de:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(700, 460, 150, 20);

        ListaFormularios.setBackground(new java.awt.Color(218, 213, 200));
        ListaFormularios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ListaFormularios.setText("Sementes");
        ListaFormularios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaFormulariosActionPerformed(evt);
            }
        });
        getContentPane().add(ListaFormularios);
        ListaFormularios.setBounds(680, 480, 190, 160);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioButtonActionPerformed
       this.dispose();
       new Gerenciamento().setVisible(true);
    }//GEN-LAST:event_usuarioButtonActionPerformed

    private void formularioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formularioButton1ActionPerformed
        this.dispose();
       new Formulario().setVisible(true);
    }//GEN-LAST:event_formularioButton1ActionPerformed

    private void ListaFormulariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaFormulariosActionPerformed
        this.dispose();
        new FuncionarioFormularios().setVisible(true);
    }//GEN-LAST:event_ListaFormulariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSelecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSelecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSelecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSelecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSelecao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ListaFormularios;
    private javax.swing.JToggleButton formularioButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToggleButton usuarioButton;
    // End of variables declaration//GEN-END:variables
}
