/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface.funcionario;

import DAO.ConexaoFormulario;
import Modelo.ContatoFormulario;
import java.text.SimpleDateFormat;

/**
 *
 * @author jonat
 */
public class VisualizarFormulario extends javax.swing.JFrame {
        int id;
    /**
     * Creates new form VisualizarFormulario
     */
    public VisualizarFormulario() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(236, 236, 220));
        descricaoField.setLineWrap(true);
        descricaoField.setWrapStyleWord(true);
            
    }
    
    public VisualizarFormulario(int id) {
            initComponents();
            descricaoField.setLineWrap(true);
            descricaoField.setWrapStyleWord(true);
            if (descricaoField != null) {
            descricaoField.setLineWrap(true);
            descricaoField.setWrapStyleWord(true);
            }
            getContentPane().setBackground(new java.awt.Color(236, 236, 220));
            
            this.id = id;

            ConexaoFormulario contatoFormulario = new ConexaoFormulario();
            ContatoFormulario contato = contatoFormulario.getFormularioById(id);

            nomeField.setText(contato.getNome());

            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            dataText.setText(formato.format(contato.getData()));
            System.out.println(contato.getIdade());
            idadeField.setText(contato.getIdade());
            areaInteresseField.setText(contato.getAreaInteresse());
            descricaoField.setText(contato.getDescricao()); // Corrigido
            getContentPane().setBackground(new java.awt.Color(236, 236, 220));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dataText = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        idadeField = new javax.swing.JTextField();
        areaInteresseField = new javax.swing.JTextField();
        Fechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaoField = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(460, 870));
        setPreferredSize(new java.awt.Dimension(460, 870));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(198, 180, 148));
        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 40, 46, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(198, 180, 148));
        jLabel2.setText("Idade:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 110, 46, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(198, 180, 148));
        jLabel3.setText("Área de Interesse:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 190, 128, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(198, 180, 148));
        jLabel4.setText("Descrição:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 270, 70, 17);

        dataText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dataText.setForeground(new java.awt.Color(198, 180, 148));
        dataText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dataText.setText("\n");
        getContentPane().add(dataText);
        dataText.setBounds(310, 20, 113, 25);

        nomeField.setEditable(false);
        getContentPane().add(nomeField);
        nomeField.setBounds(20, 60, 400, 46);

        idadeField.setEditable(false);
        getContentPane().add(idadeField);
        idadeField.setBounds(20, 140, 400, 46);

        areaInteresseField.setEditable(false);
        getContentPane().add(areaInteresseField);
        areaInteresseField.setBounds(20, 220, 400, 46);

        Fechar.setBackground(new java.awt.Color(218, 213, 200));
        Fechar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Fechar.setForeground(new java.awt.Color(198, 180, 148));
        Fechar.setText("Fechar");
        Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharActionPerformed(evt);
            }
        });
        getContentPane().add(Fechar);
        Fechar.setBounds(155, 770, 125, 50);

        descricaoField.setEditable(false);
        descricaoField.setColumns(20);
        descricaoField.setRows(5);
        jScrollPane1.setViewportView(descricaoField);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 290, 400, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharActionPerformed
      this.dispose();
    }//GEN-LAST:event_FecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizarFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizarFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizarFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizarFormulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fechar;
    private javax.swing.JTextField areaInteresseField;
    private javax.swing.JLabel dataText;
    private javax.swing.JTextArea descricaoField;
    private javax.swing.JTextField idadeField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeField;
    // End of variables declaration//GEN-END:variables
}
